name = "Craftoria"
author = "TeamAOE"
version = "1.31.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07de2b5510dbd0062efd7cb46ebc1686459f5bba54dafa2d469324bd2778d011"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
