name = "Forktoria"
author = "TeamAOE"
version = "1.0.0b3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e16eb3f20c4257c5dbd6fa8251d52cdc5181134e143a556941f2234513535ca"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
