name = "Forktoria"
author = "TeamAOE"
version = "1.0.0b1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8df15753bafdabbb07ba9b01e43a00a368677802cdeef6587bdddc684d50cf96"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
